### ISSUE TITLE
segmentation fault while removing api-gateway

### ISSUE THREAD

**Issue by hariseldon78** [gruntwork-io/cloud-nuke#765]
Hello, I got the following error with this command line: 
`cloud-nuke aws --exclude-resource-type iam --exclude-resource-type iam-group --exclude-resource-type iam-policy --exclude-resource-type iam-role --exclude-resource-type iam-service-linked-role`
```
 WARNING  THE NEXT STEPS ARE DESTRUCTIVE AND COMPLETELY IRREVERSIBLE, PROCEED WITH CAUTION!!!

Are you sure you want to nuke all listed resources? Enter 'nuke' to confirm (or exit with ^C) : nuke
Nuking batch of 3 apigateway resource(s) in eu-central-1 [39/925]  4% | 42spanic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x5e53f19bdae5]

goroutine 18757 [running]:
github.com/gruntwork-io/cloud-nuke/aws/resources.(*ApiGateway).removeAttachedClientCertificates(0xc00136dbc0, {0xc000114538, 0x1, 0xc001883c80?})
        github.com/gruntwork-io/cloud-nuke/aws/resources/apigateway.go:93 +0x65
github.com/gruntwork-io/cloud-nuke/aws/resources.(*ApiGateway).nukeAsync(0xc00136dbc0, 0xc000da2fd0?, 0xc000fd3440, 0xc0013e0860)
        github.com/gruntwork-io/cloud-nuke/aws/resources/apigateway.go:116 +0x148
created by github.com/gruntwork-io/cloud-nuke/aws/resources.(*ApiGateway).nukeAll in goroutine 1
        github.com/gruntwork-io/cloud-nuke/aws/resources/apigateway.go:53 +0x17f

```

using the version 0.37.1-1 from the arch linux aur package "aur/cloud-nuke" (built at install, not the binary version)

**Comment by james03160927** [comment]
HI @hariseldon78, this should have been fixed with the latest release. Can you try using the latest version? https://github.com/gruntwork-io/cloud-nuke/releases/tag/v0.37.2

**Comment by james03160927** [comment]
Closing this issue. Let us know if you continue to face the same issue.
